version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
        # sites folder
          - ./sites:/var/www
        # config folder
          - ./config/nginx:/etc/nginx/conf.d
        # logs folder
          - ./data/logs:/var/log/nginx/
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./sites:/var/www
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
          - ./data/mysql:/var/lib/mysql
        ports:
            - 3306:3306