version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
        # sites folder
          - ./sites:/var/www
        # config folder
          - ./config/nginx:/etc/nginx/conf.d
        # logs folder
          - ./data/logs:/var/log/nginx/
        depends_on:
          - php
          - mysql
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
          - ./sites:/var/www
          - ./config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
          - ./config/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    mysql:
        image: mariadb:latest
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        command: --innodb_use_native_aio=0
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
          - ./data/mysql:/var/lib/mysql
        ports:
            - 3306:3306