version: '3'
services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
        # sites folder
          - ./sites:/var/www
        # config folder
          - ./config/nginx:/etc/nginx/conf.d
        # logs folder
          - ./data/logs:/var/log/nginx/
        depends_on:
          - php
          - mysql
        networks:
          - app-network
    php:
        container_name: php
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
          - ./sites:/var/www
          # XDEBUG. We can config php.ini (/usr/local/etc/php/php.ini) or we can create separate file xdebug.ini and place it on "/usr/local/etc/php/conf.d/" folder
          - ./config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
          # Enable config for reporting about all error
          - ./config/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        ports:
          #for laravel. Command for start lavaver is php artisan serve --host 0.0.0.0
            - 8000:8000    
        networks:
          - app-network
            
    mysql:
        container_name: mysql
        image: mariadb:latest
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        command: --innodb_use_native_aio=0
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
          - ./data/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
          - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
